"""Normalize delombok output into idiomatic Java source.

delombok emits semantically exact expansions, but leaves migration-only
artifacts behind: a timestamp header, ``@SuppressWarnings("all")`` on every
generated member, and ``$``-separated internal identifiers. This script removes
those artifacts so the result reads as ordinary handwritten Java. It rewrites
identifiers only; generated behaviour is left intact.

Usage:
    python delombok_clean.py <source-root>
"""
from pathlib import Path
import re
import sys

# Matches the delombok banner, e.g. "// Generated by delombok at Mon Sep ...".
HEADER = re.compile(r"^// Generated by delombok at .*\n")

# `@java.lang.SuppressWarnings("all")` lines, with the annotation's own line only
# so surrounding Javadoc stays put.
SUPPRESS = re.compile(r"^[ \t]*@java\.lang\.SuppressWarnings\(\"all\"\)[ \t]*\r?\n", re.MULTILINE)

# delombok fully qualifies these; the expanded sources need no import for them.
DEFAULT_IMPORTS = [
    ("java.lang.Object", "Object"),
    ("java.lang.String", "String"),
    ("java.lang.Override", "Override"),
    ("java.lang.Character", "Character"),
]

# Internal identifier forms, replaced in this order. `$default$foo` must run
# before the generic `$foo` rule or it would be split at the wrong boundary.
IDENTIFIERS = [
    # private static helpers backing @Builder.Default
    (re.compile(r"\$default\$(\w+)"), lambda m: "default" + m.group(1)[:1].upper() + m.group(1)[1:]),
    # builder field/flag pairs: `foo$value` and `foo$set`
    (re.compile(r"\b(\w+)\$value\b"), lambda m: m.group(1) + "Value"),
    (re.compile(r"\b(\w+)\$set\b"), lambda m: m.group(1) + "Set"),
    # equals() locals
    (re.compile(r"\bthis\$(\w+)"), lambda m: "this" + m.group(1)[:1].upper() + m.group(1)[1:]),
    (re.compile(r"\bother\$(\w+)"), lambda m: "other" + m.group(1)[:1].upper() + m.group(1)[1:]),
    # hashCode() locals
    (re.compile(r"(?<![\w$])\$(\w+)"), lambda m: "hash" + m.group(1)[:1].upper() + m.group(1)[1:]),
]


def clean(text):
    """Return `text` with delombok-only artifacts removed."""
    text = HEADER.sub("", text, count=1)
    text = SUPPRESS.sub("", text)
    for qualified, simple in DEFAULT_IMPORTS:
        text = text.replace(qualified, simple)
    for pattern, repl in IDENTIFIERS:
        text = pattern.sub(repl, text)
    return text


def main():
    """Clean every Java file under the given root in place."""
    root = Path(sys.argv[1] if len(sys.argv) > 1 else "backend/business")
    files = sorted(p for p in root.rglob("*.java"))
    for path in files:
        raw = path.read_bytes()
        newline = b"\r\n" if raw.count(b"\r\n") else b"\n"
        text = raw.decode("utf-8").replace("\r\n", "\n")
        path.write_bytes(clean(text).replace("\n", newline.decode()).encode("utf-8"))
    print(f"cleaned {len(files)} files")


if __name__ == "__main__":
    main()
