/**
 * 简体中文本地化文案 —— 唯一文案来源。
 * 组件内禁止散落 UI 文案，一律从这里取值。
 */
export const copy = {
  brand: '番组手账',

  navigation: {
    home: '首页',
    schedule: '放送时间表',
    myCollection: '我的追番',
    login: '登录',
    register: '注册',
    logout: '退出登录',
    profile: '个人资料',
    theme: '主题',
    language: '语言',
    ai: 'AI 助手',
    primary: '主导航',
    mobile: '移动端主导航',
    userMenu: '用户菜单',
  },

  search: {
    label: '搜索番剧',
    placeholder: '搜索番剧、标签或关键词',
    trigger: '搜索',
    submit: '搜索',
    suggestions: '搜索建议',
    history: '搜索历史',
    clear: '清空',
    empty: '没有找到相关结果',
    keyword: '关键词',
  },

  common: {
    theme: '主题',
    light: '浅色',
    dark: '深色',
    system: '跟随系统',
    loading: '加载中…',
    error: '加载失败',
    retry: '重试',
    empty: '暂无内容',
    all: '全部',
    cancel: '取消',
    confirm: '确认',
    close: '关闭',
    back: '返回',
    more: '更多',
    notAvailable: '暂无',
    requestId: '请求编号',
  },

  subject: {
    cover: '封面',
    scoreUnit: '分',
    episodeUnit: '集',
    episodesAll: '全 {{total}} 集',
    seasons: ['冬', '春', '夏', '秋'],
  },

  home: {
    tagline: '发现番剧，记录追番',
    seasonal: '本季新番',
    popular: '热门作品',
    todaySchedule: '今日放送',
    continueWatching: '继续观看',
    todayUpdates: '今日更新',
    collectionOverview: '收藏概览',
    recommended: '为你推荐',
    viewAll: '查看全部',
    viewAllCollection: '查看全部追番',
    welcomeBack: '欢迎回来',
    loadError: '首页加载失败，请稍后重试',
  },

  discovery: {
    title: '发现',
    keywordPlaceholder: '输入关键词',
    season: '季度',
    tag: '标签',
    type: '类型',
    status: '状态',
    sort: '排序',
    sortPopular: '按热度',
    sortScore: '按评分',
    sortNewest: '按新度',
    filter: '筛选',
    reset: '重置',
    previous: '上一页',
    next: '下一页',
    results: '共 {{total}} 条结果',
    empty: '没有找到符合条件的番剧',
  },

  detail: {
    overview: '简介',
    episodes: '剧集',
    score: '评分',
    year: '年份',
    season: '季度',
    tags: '标签',
    airedAt: '放送时间',
    lastEpisode: '最新一集',
    collectionStatus: '追番状态',
    addToCollection: '加入追番',
    removeFromCollection: '移除追番',
    notInCollection: '尚未追番',
    share: '分享',
  },

  schedule: {
    title: '放送时间表',
    today: '今天',
    timezone: '时区',
    empty: '当天暂无更新',
    weekdays: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    statusAiring: '放送中',
    statusFinished: '已完结',
    statusUpcoming: '未放送',
  },
} as const;

export type Copy = typeof copy;
