from typing import Protocol, runtime_checkable

from app.chat.models import Message, Session
from app.schemas.pending_action import PendingAction


@runtime_checkable
class ChatStore(Protocol):
    async def init_db(self) -> None: ...
    async def create_session(self, user_id: int, session_id: str, title: str = "新对话") -> None: ...
    async def get_user_sessions(self, user_id: int) -> list[Session]: ...
    async def get_messages(self, session_id: str) -> list[Message]: ...
    async def save_message(
        self,
        session_id: str,
        role: str,
        content: str,
        tool_calls: str | None = None,
    ) -> None: ...
    async def delete_session(self, session_id: str, user_id: int) -> None: ...
    async def update_session_title(self, session_id: str, title: str) -> None: ...
    async def get_pending_action(self, session_id: str, user_id: int) -> PendingAction | None: ...
    async def save_pending_action(
        self,
        session_id: str,
        action: PendingAction,
        ttl_seconds: int = 600,
    ) -> None: ...
    async def delete_pending_action(self, session_id: str, user_id: int) -> None: ...
