import { get, post } from '../http';
export const prompts = () => get<Record<string, unknown>>('/admin/agent/prompts');
export const promptDetail = (key: string) => get<Record<string, unknown>>(`/admin/agent/prompts/${encodeURIComponent(key)}`);
export const promptUpdate = (key: string, d: Record<string, unknown>) => post<Record<string, unknown>>(`/admin/agent/prompts/${encodeURIComponent(key)}/update`, d);
export const promptReset = (key: string) => post<void>(`/admin/agent/prompts/${encodeURIComponent(key)}/reset`);
export const config = () => get<Record<string, unknown>>('/admin/agent/config');
export const configUpdate = (d: Record<string, unknown>) => post<void>('/admin/agent/config/update', d);
export const chatSessions = () => get<Record<string, unknown>[]>('/admin/agent/chat/sessions');
export const chatCreateSession = () => post<Record<string, unknown>>('/admin/agent/chat/sessions', {});
export const chatHistory = (sessionId: string) => get<Record<string, unknown>[]>(`/admin/agent/chat/sessions/${encodeURIComponent(sessionId)}/history`);
export const chatDeleteSession = (sessionId: string) => post<void>(`/admin/agent/chat/sessions/${encodeURIComponent(sessionId)}/remove`);
export const chatStreamBody = (message: string, sessionId?: string) => ({ message, ...(sessionId ? { sessionId } : {}) });
